apiVersion: v1
kind: Secret
metadata:
  name: kafka-consumer-secret
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka-credentials
    app.kubernetes.io/part-of: confluent-client
type: Opaque
stringData:
  KAFKA_USERNAME: "admin"
  KAFKA_PASSWORD: "adminpassword"
